### ISSUE TITLE
Version inconsistency

### ISSUE THREAD

**Issue by politician** [cisagov/action-lineage#58]
The versions of this action are inconsistent.

## Problem

I found a [v0.1.0 tag](https://github.com/cisagov/action-lineage/releases/tag/v0.1.0) that links to a commit more recent than the [v1.0.0 branch](https://github.com/cisagov/action-lineage/tree/v1.0.0).

## Solution

I recommend to keep working on your main branch (develop in your case) and tag new versions along.

You could enforce [conventional commit](https://www.conventionalcommits.org) messages and then use [tools](https://www.conventionalcommits.org/en/about/) to automate new releases and changelogs and make your life easier.

**Comment by mcdonnnj** [comment]
Thank you for your interest in our project!

The [v1.0.0](https://github.com/cisagov/action-lineage/tree/v1.0.0) branch is a work-in-progress branch (that needs a rebase to update it against `develop`). We do not maintain versioned branches, so when that branch is merged into [develop](https://github.com/cisagov/action-lineage/tree/develop) a new `v1.0.0` tag will be created and the branch will be deleted. I'm sorry if that was unclear.

We do not currently have any plans to adopt something like Conventional Commits. I personally do not think that they align very well with our preferred development style as we encourage committing early and often as well as explicitly not performing squash merges, Regardless of my personal opinion it would be a team decision to implement such a thing into our development standards.
